### PR TITLE
Add support for node 4.x versions (latest)

### PR DESCRIPTION
**Pull request by Yanchek99**
Adding support for node 4.x and setting the default version to the
latest (4.2)

Removed version check as the documentation in the defaults file should
be enough.

Cleaned up docker file to use latest ansible.

Cleaned up role.yml to run the source as a role rather then including the main task file.

Cleaned up the task file to better represent yaml.

docker build . 
```
Step 11 : RUN node -v
 ---> Running in fd9f9b532976
v4.2.1
 ---> 11d0faf48a7c
```

### CODE REVIEW

**Comment by wyaeld** [comment]
:+1: @rvagg can you or a maintainer review.  Would like be able to use this from galaxy

**Comment by wolfeidau** [comment]
Did some testing and it looks great so now merged.

Just need @rvagg to push to galaxy!

**Comment by tphummel** [comment]
Looks good for me re: #16. Thanks!

**Comment by rvagg** [comment]
I pressed re-import but I really have no idea if that's done anything, Galaxy seems to be lacking something to show you what's happened & when.

**Comment by wolfeidau** [comment]
Just confirmed new version is being served by galaxy.

Cheers @rvagg

**Pull request merged**
